name: dentaku
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2
dependencies:
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.3
  very_good_analysis: ^10.0.0

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  
flutter:
  uses-material-design: true
